---
- name: create directory for putting ceph-ansible sample variable files
  file:
    path: /usr/share/ceph-ansible/group_vars/sample
    state: directory
    mode: 0755

- name: Move sample files to sample directory
  command: "mv /usr/share/ceph-ansible/group_vars/*.sample /usr/share/ceph-ansible/group_vars/sample"
  args:
    creates: /usr/share/ceph-ansible/group_vars/sample/all.yml
  tags: skip_ansible_lint

- name: Place prepared ceph-ansible group_vars
  copy:
    src: "{{ item }}"
    dest: "/usr/share/ceph-ansible/group_vars/{{ item }}"
  with_items:
    - all.yml
    - osds.yml
    - clients.yml

- name: Remove default ansible host file
  file:
    path: /etc/ansible/hosts
    state: absent

- name: Rename ceph-ansible site.yml
  command: "mv /usr/share/ceph-ansible/site-docker.yml.sample /usr/share/ceph-ansible/site.yml"
  args:
    creates: /usr/share/ceph-ansible/site.yml
  tags: skip_ansible_lint

- name: set ansible to be less chatty for ceph-ansible
  lineinfile:
    path: /usr/share/ceph-ansible/ansible.cfg
    line: "{{ item.line }}"
    insertafter: "{{ item.after }}"
    state: present
  with_items:
    - line: "stdout_callback = actionable"
      after: '^\[defaults\]$'
    - line: "deprecation_warnings = False"
      after: '^\[defaults\]$'
    - line: "command_warnings = False"
      after: '^\[defaults\]$'
    - line: "pipelining=True"
      after: '^\[ssh_connection\]$'

- name: Ensure ansible log file exists
  copy:
    content: ""
    dest: /var/log/ansible.log
    force: no
    group: student
    owner: student
    mode: 0644

- name: enable and start chronyd service
  systemd:
    name: chronyd
    enabled: yes
    state: started
...
