---
- name: upgrade all packages
  package:
    name: '*'
    state: latest

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts

- name: Install initial packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"

- name : Get s3cmd package
  get_url:
    url: https://raw.githubusercontent.com/red-hat-storage/ceph-test-drive-bootstrap/ceph-test-drive-packer/rhcs3.0/packer/roles/rhcs-prerequisite/files/s3cmd-2.0.1-1.el7.noarch.rpm
    dest: /tmp/s3cmd-2.0.1-1.el7.noarch.rpm

- name: Install S3cmd
  yum: 
    name: /tmp/s3cmd-2.0.1-1.el7.noarch.rpm 
    state: present

- name: Download RHCS 3.0 from S3
  get_url:
    url: https://s3.amazonaws.com/karansingh/test-drive/rhceph-3.0-rhel-7-x86_64.iso
    dest: /home/student/rhceph-3.0-rhel-7-x86_64.iso

- import_tasks: ssh_setup.yml

- import_tasks: ceph-ansible-prepare.yml

- import_tasks: ceph-metrics-prepare.yml
