---
- name: upgrade all packages
  package:
    name: '*'
    state: latest

- name: Setting up repos for sysbench
  shell: "curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash"
  ignore_errors: true

- name: Install initial packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"
  ignore_errors: true

- name : Get s3cmd package
  get_url:
    url: https://raw.githubusercontent.com/red-hat-storage/ceph-test-drive-bootstrap/ceph-test-drive-packer/rhcs3.0/packer/roles/rhcs-prerequisite/files/s3cmd-2.0.1-1.el7.noarch.rpm
    dest: /tmp/s3cmd-2.0.1-1.el7.noarch.rpm

- name: Install S3cmd
  yum: 
    name: /tmp/s3cmd-2.0.1-1.el7.noarch.rpm 
    state: present

- name : Install epel
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present 

- name : Instal PIP
  package:
    name: python-pip
    state: present

- name : Install python-swiftclient
  shell: "pip install --upgrade pip; pip install python-swiftclient"

- name: Remove epel
  package:
    name: epel-release
    state: absent  

- name: Download RHCS 3.0 from S3
  get_url:
    url: https://s3.amazonaws.com/karansingh/test-drive/rhceph-3.0-rhel-7-x86_64.iso
    dest: /home/student/rhceph-3.0-rhel-7-x86_64.iso

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts

- import_tasks: ssh_setup.yml

- import_tasks: ceph-ansible-prepare.yml

- import_tasks: ceph-metrics-prepare.yml
