---
- name: upgrade all packages
  package:
    name: '*'
    state: latest
  tags: skip_ansible_lint

# yamllint disable rule:line-length
- name: Setting up repos for sysbench
  shell: |
    set -o pipefail
    curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash
  tags: skip_ansible_lint
# yamllint enable

- name: Install initial packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"

- name: Install S3cmd
  yum:
    name: https://s3.amazonaws.com/karansingh/test-drive/s3cmd-2.0.1-1.el7.noarch.rpm
    state: present

- name: Install epel
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install PIP
  package:
    name: python-pip
    state: present

- name: Install python-swiftclient
  pip:
    name:
      - pip
      - python-swiftclient
      - flask
    state: latest
  tags: skip_ansible_lint

- name: Remove epel
  package:
    name: epel-release
    state: absent

- name: Download Image and Video for object storage module
  get_url:
    url: "{{ item }}"
    dest: /home/student/
  with_items:
    - https://s3.amazonaws.com/karansingh/test-drive/Red_Hat_Tower.jpg
    - https://s3.amazonaws.com/karansingh/test-drive/Red_Hat_Ceph_Storage.mp4

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts

- import_tasks: ssh_setup.yml

- import_tasks: ceph-ansible-prepare.yml

- import_tasks: ceph-sree-prepare.yml

- import_tasks: docker-prepare.yml
