---

- name: "Set {{ item.key }} {{ item.value }} for sshd"
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    regexp: "{{ appendToRegex | default('') }}{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  with_items:
    - key: StrictHostKeyChecking
      value: no
      appendToRegex: ^
    - key: ClientAliveInterval
      value: 600
      appendToRegex: "#"
    - key: ClientAliveCountMax
      value: 3
      appendToRegex: "#"
    - key: UseDNS
      value: no
      appendToRegex: ^
    - key: PasswordAuthentication
      value: yes
      appendToRegex: ^
    - key: GSSAPIAuthentication
      value: no
      appendToRegex: ^
