---

- name: "Set {{ item.key }} {{ item.value }} for sshd"
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ prependToRegex | default('') }}{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  with_items:
    - key: ClientAliveInterval
      value: 600
      prependToRegex: "#"
    - key: ClientAliveCountMax
      value: 3
      prependToRegex: "#"
    - key: UseDNS
      value: no
      prependToRegex: ^
    - key: PasswordAuthentication
      value: yes
      prependToRegex: ^
    - key: GSSAPIAuthentication
      value: no
      prependToRegex: ^

- name: Disable strict Hostkey checking
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: "^StrictHostKeyChecking"
    line: StrictHostKeyChecking no