---

- name: Set StrictHostKeyChecking NO for sshd
  lineinfile:
    path: /etc/ssh/ssh_config
    state: present
    regexp: "{{ appendToRegex | default('') }}{{ key }}"
    line: "{{ key }} {{ value }}"
  with_items:
    - key: StrictHostKeyChecking
      value: no
      appendToRegex: ^
    - key: ClientAliveInterval
      value: 600
      appendToRegex: "#"
    - key: ClientAliveCountMax
      value: 3
      appendToRegex: "#"
    - key: UseDNS
      value: no
      appendToRegex: ^
    - key: PasswordAuthentication
      value: yes
      appendToRegex: ^
    - key: GSSAPIAuthentication
      value: no
      appendToRegex: ^
