#site_name: RHCS Test Drive Instructions
site_favicon: images/favicon.ico
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - footnotes
    - smart_strong
    - codehilite
    - nl2br
    
#theme: 'united'
#extra:
#    theme_inverse: true
#pages:
#- Home: index.md
#- Modules:
#    - 'Module 1 - Setting up a Ceph cluster': Module-1.md
#    - 'Module 2 - Ceph Block Storage interface': Module-2.md
#    - 'Module 3 - Ceph Object Storage interface': Module-3.md
#    - 'Module 4 - Scaling up a Ceph cluster': Module-4.md


theme: 'material'
extra:
  logo: 'images/RedHat.svg'
site_name: Red Hat Ceph Storage Test Drive
site_url: https://red-hat-storage.github.io/ceph-test-drive-bootstrap

pages:
- Home: index.md
- Modules:
    - 'Module-1 Ceph Cluster Setup': Module-1.md
    - 'Module-2 Ceph Block Storage': Module-2.md
    - 'Module-3 Ceph Object Storage': Module-3.md
 #   - 'Module 4 - Scaling up a Ceph cluster': Module-4.md

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

copyright: Copyright ©2016 Red Hat, Inc.
