---
- name: install CNS deployment tools
  yum: name={{ item }} state=present
  with_items:
    - cns-deploy-4.0.0-19.el7rhgs
    - heketi-client-4.0.0-10.el7rhgs

- name: heketi DeploymentConfig definitions to run on infa nodes
  patch:
    src: "{{ item }}.patch"
    dest: "/usr/share/heketi/templates/{{ item }}.yaml"
  with_items:
    - deploy-heketi-template
    - heketi-template
...
