---

- block:

  - name: remove rhui-client packages
    yum: name=rh-amazon-rhui-client* state=absent

  - name: clean yum cache
    shell:
      cmd: yum clean all
      warn: false
    ignore_errors: true
    tags: skip_ansible_lint

  - name: enable Red Hat product id support in yum
    copy: src=product-id.conf dest=/etc/yum/pluginconf.d/

  when: disable_rhui

# - name: ensure organization id is supplied
#   fail:
#     msg: "You must supply an RHSM organization ID"
#   when:
#     - (rhsm_org_id is not defined or rhsm_org_id)

# - name: ensure activation key is supplied
#   fail:
#     msg: "You must supply an RHSM activation key"
#   when:
#     - (rhsm_act_key is not defined or rhsm_act_key)

# - name: ensure repositories are supplied
#   fail:
#     msg: "You must supply at least one RHSM repository"
#   when:
#     - (rhsm_repos is not defined or rhsm_repos|length == 0)

- name: registering system with CDN
  register: rhn_registration
  redhat_subscription:
    autosubscribe: false
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool: "Employee SKU"
    # org_id: "{{ rhsm_org_id }}"
    # activationkey: "{{ rhsm_act_key }}"
    # state: present
    force_register: true
    # pool_ids: 8a85f98260c27fc50160c328c08a5045
  notify:
    - disable all default repositories
    - enable all required repositories

- name: Ensure handlers are run
  meta: flush_handlers

...
