---

- name: disable all default repositories
  rhsm_repository:
    name: '*'
    state: disabled
  ignore_errors: yes

- name: enable all required repositories
  rhsm_repository:
    name: "{{ rhsm_repos }}"

...