---
- name: create cloud-user account
  user:
    name: cloud-user
    password: '$6$0QTKiAxX5.ONsPxA$keFvFhrX6cRqYiN4OLSezEopULJFO4da7K7hl2sromKY69CvumfAgotEB9K1gmcjakjrdEkbA2Ku6m2Rsry9D0'
    generate_ssh_key: yes

- name: fetch ssh pub key
  fetch:
    src: /home/cloud-user/.ssh/id_rsa.pub
    dest: fetch/
    flat: yes

- name: fetch ssh private key
  fetch:
    src: /home/cloud-user/.ssh/id_rsa
    dest: fetch/
    flat: yes

- name: add ssh key pair to authorized_keys
  authorized_key:
    user: cloud-user
    key: "{{ lookup('file', 'fetch/id_rsa.pub') }}"
    state: present

...
