---

disable_rhui: true

rhsm_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-rhceph-3-tools-rpms
  - rhel-7-server-ansible-2.6-rpms
  # - rhel-7-server-rhceph-3-mon-rpms
  # - rhel-7-server-rhceph-3-osd-rpms

...
