---
dummy:
fetch_directory: ~/ceph-ansible-keys

ceph_docker_image: rhceph/rhceph-3-rhel7
ceph_docker_image_tag: "3"
containerized_deployment: true
ceph_docker_registry: registry.access.redhat.com

monitor_interface: eth0
# mon_use_fqdn: true
public_network: 10.100.0.0/16
# osd_objectstore: filestore

radosgw_civetweb_port: 80
radosgw_civetweb_num_threads: 512
radosgw_civetweb_options: "num_threads={{ radosgw_civetweb_num_threads }}"
radosgw_interface: eth0
radosgw_dns_name: "ceph-admin"

ceph_conf_overrides:
  global:
    osd pool default pg num: 64
    osd pool default pgp num: 64
    mon allow pool delete: true
    mon clock drift allowed: 5
    rgw dns name: "ceph-admin"
