---

  - name: Ensure lab directory exists
    file:
      path: /opt/lab/helpers
      state: directory
      owner: cloud-user
      group: cloud-user
      mode: "u=rwx,g=r,o=r"

  - name: Copy idm certificate playbook
    copy:
      src: fetch_idm_cert.yml
      dest: /opt/lab/helpers/
      owner: cloud-user
      group: cloud-user
      mode: "u=rw,g=r,o=r"

...
